data = 'welcome to first app in python'
print(type(data))
print(data[0])
print(len(data))
data.lower()
data.upper()
data.split()
data.split('i')
x = data.split()
print(x)
y = ':'.join(x)
print(y)
data.find('fist')
print(data[11])
print(data[11:16])
print(data.capitalize())
number = 20
print('number is {}'.format(20))
print('number is {} as lower while {} is as upper'.format(20, 50))
